language: python
sudo: false
python:
  - "2.7"
install:
  - pip install .
  - pip install numpy twisted
  - pip install pytest coveralls
env:
  - SCALABRAD_VERSION=0.3.3
cache:
  directories:
    - $HOME/scalabrad-$SCALABRAD_VERSION
before_script:
  - bash scripts/test/install-scalabrad.sh
  - export PATH=$PATH:$HOME/scalabrad-$SCALABRAD_VERSION/bin/
script: scripts/test/test.sh
after_success:
  - coveralls

